name: Chore
description: Requests for cleaning up code or updating packages
title: "[Chore] - "
labels: ["chore"]
assignees: jdwilkin4
body:
  - type: markdown
    attributes:
      value: "# Chore request"
  - type: textarea
    id: description
    attributes:
      label: What work needs to be done?
      description: Please explain what work needs to be done in as much detail as possible
    validations:
      required: true
