// array for performance outcomes
const gigResponses = [
  "You tried out a new song but the audience hated it",
  "A local musician heard your show and asked to collaborate in the future",
  "You tried out a new song and the audience loved it",
  "Your show started off strong but the ending was bad",
  "Your show started off rocky but you ended strong",
  "A little kid came up to you after the gig and congratulated you",
  "A local bar owner saw your show and asked if you could play at their bar",
  "The gig went well but the club manager was a jerk",
  "Someone approaches you after the show and asks for an autograph",
  "Your performance was ok and received a chilly reception from the audience",
  "People were dancing the whole time and really enjoyed your set",
  "You ran into an old jazz friend and got drinks after the show",
  "There was a heckler in the audience but you kept performing anyway",
  "You were running late to the gig but the performance went well",
  "You got sick before the show so you did not perform well",
  "You got into an argument with the manager of the club and they cut your set short.",
  "You were not allowed to use the bathroom because it is for whites only.",
  "You received a standing ovation!",
  "You stumbled a little bit during the set and received a few boos onstage.",
  "An agent was impressed by your set and wants to speak with you.",
  "A record executive was impressed by your set and want to speak with you.",
  "A local celebrity heard you perform and was really impressed.",
  "A major celebrity heard you perform and invited you to hang with them afterwards.",
  "A publishing executive heard your performance and wants to speak with you.",
  "A famous jazz musician was impressed by your set and wants to speak with you.",
];

export default gigResponses;
