const instrumentalists = [
  {
    name: "Abbitt, Taylor",
    tag: "Double Bassist",
    bio: "http://www.instrumentalcasting.com/viewmusiciang.php?serial=881",
    image: "/images/Taylor-Abbitt.jpg",
    alt: "Taylor Abbitt",
    category: "strings",
  },
  {
    name: "Abraham, Dr.Immanuel Tzemach(b.1990)",
    tag: "Composer, clinician, teacher, and violinist",
    bio: "https://www.theviolindoctor.org/",
    image: "/images/immanuel-Abraham.jpg",
    alt: "Dr.Immanuel Tzemach Abraham",
    category: "strings",
  },
  {
    name: "Abrams, Muhal Richard (1930 – 2017)",
    tag: "Educator, composer, arranger and pianist",
    bio: "https://en.wikipedia.org/wiki/Muhal_Richard_Abrams",
    image: "/images/Muhal_Richard_Abrams.jpg",
    alt: "Muhal Richard Abrams",
    category: "piano",
  },
  {
    name: "Adam, Miriam",
    tag: "Clarinetist",
    bio: "https://centerstage.conn-selmer.com/artists/mariam-adam",
    image: "/images/mariam-adams.jpg",
    alt: "Miriam Adam",
    category: "woodwinds",
  },
  {
    name: "Adams, Armenta ",
    tag: "Pianist",
    bio: "https://en.wikipedia.org/wiki/Armenta_Adams",
    image: "/images/armenta-adams.jpg",
    alt: "Armenta Adams",
    category: "piano",
  },
  {
    name: "Adams, Harrison Leslie (b. 1932)",
    tag: "Composer, Pianist & Professor",
    bio: "http://chevalierdesaintgeorges.homestead.com/Adams.html",
    image: "/images/H_leslie_adams.jpg",
    alt: "Harrison Adams",
    category: "piano",
  },
  {
    name: "Adedamola, Sydney",
    tag: "Violinist",
    bio: "https://www.laphil.com/musicdb/artists/7764/sydney-adedamola",
    image: "/images/Sydney-Adedamola.jpg",
    alt: "Sydney Adedamola",
    category: "strings",
  },
  {
    name: "Alabaca, Ahmed",
    tag: "Composer, conductor, pianist",
    bio: "https://www.ahmedalabaca.com/bio",
    image: "/images/Ahmed-Alabaca.jpg",
    alt: "Ahmed Alabaca",
    category: "piano",
  },
  {
    name: "Alberga, Eleanor (b. 1949)",
    tag: "Jamaican Composer & Pianist",
    bio: "http://chevalierdesaintgeorges.homestead.com/Alberga.html",
    image: "/images/alberga-eleanor.jpg",
    alt: "Eleanor Alberga",
    category: "piano",
  },
  {
    name: "Alexander II, Glenn",
    tag: "Pianist and conductor",
    bio: "https://www.chicagosinfonietta.org/glenn-alexander-ii/",
    image: "/images/Glenn-Alexander-II.jpg",
    alt: "Glenn Alexander II",
    category: "piano",
  },
  {
    name: "Ali-Landing, Ifetayo",
    tag: "Cellist",
    bio: "https://www.sphinxmusic.org/bio-ifetayo-ali/",
    image: "/images/ifetayoali-cello.jpg",
    alt: "Ifetayo Ali-Landing",
    category: "strings",
  },
  {
    name: "Allen-Batieste, DeMarus",
    tag: "Clarinetist",
    bio: "https://www.linkedin.com/in/demarus-allen-batieste-125bb424",
    image: "/images/demarus-batieste.jpg",
    alt: "DeMarus Allen-Batieste",
    category: "woodwinds",
  },
  {
    name: "Armstrong, Lillian Hardin (1898 – 1971)",
    tag: "Jazz pianist, composer, and arranger",
    bio: "https://en.wikipedia.org/wiki/Lil_Hardin_Armstrong",
    image: "/images/Lilian-Armstrong.jpg",
    alt: "Lil Hardin Armstrong",
    category: "piano",
  },
  {
    name: "Armstrong, Louis Daniel (1901 – 1971)",
    tag: "Trumpeter, singer and composer",
    bio: "https://en.wikipedia.org/wiki/Louis_Armstrong",
    image: "/images/Louis_Armstrong.jpg",
    alt: "Louis Armstrong",
    category: "brass",
  },
  {
    name: "Bailey, Sandra ",
    tag: "Bassoonist",
    bio: "https://www.arkansassymphony.org/sandra-bailey",
    image: "/images/bailey-sandra.jpg",
    alt: "Sandra Bailey",
    category: "woodwinds",
  },
  {
    name: "Barefield, Edward Emanuel (1909 – 1991)",
    tag: "Saxophonist, composer and arranger",
    bio: "https://en.wikipedia.org/wiki/Eddie_Barefield",
    image: "/images/Edward-barefield.jpg",
    alt: "Edward Barefield",
    category: "woodwinds",
  },
  {
    name: "Blackwell, Alfonzo (b. 1971)",
    tag: "Jazz saxophonist, composer, and producer",
    bio: "https://en.wikipedia.org/wiki/Alfonzo_Blackwell",
    image: "/images/alfonzo-blackwell.jpg",
    alt: "Alfonzo Blackwell",
    category: "woodwinds",
  },
  {
    name: 'Blake, James Hubert "Eubie" (1887 – 1983)',
    tag: "American pianist, lyricist, and composer",
    bio: "https://en.wikipedia.org/wiki/Eubie_Blake",
    image: "/images/EubieBlake.jpg",
    alt: 'James "Eubie" Blake',
    category: "piano",
  },
  {
    name: "Blanchard, Terence Oliver (b. 1962)",
    tag: "American trumpeter and composer",
    bio: "https://en.wikipedia.org/wiki/Terence_Blanchard",
    image: "/images/Terrance-Blanchard.jpg",
    alt: "Terence Blanchard",
    category: "brass",
  },
  {
    name: "Bonds, Margaret Allison (1913-1972)",
    tag: "Composer, Pianist & Musical Director ",
    bio: "http://chevalierdesaintgeorges.homestead.com/Bonds.html",
    image: "/images/Margaret-Bonds.jpg",
    alt: "Margaret Bonds",
    category: "piano",
  },
  {
    name: "Booker, Cremaine ",
    tag: "Cellist",
    bio: "https://www.thatcelloguy.com/bio",
    image: "/images/cremaine-cello.jpg",
    alt: "Cremaine Booker",
    category: "strings",
  },
  {
    name: "Braxton, Anthony (b. 1945)",
    tag: "Experimental composer, improviser, saxophonist ",
    bio: "https://en.wikipedia.org/wiki/Anthony_Braxton",
    image: "/images/anthony-braxton.jpg",
    alt: "Anthony Braxton",
    category: "woodwinds",
  },
  {
    name: "Brooks, Dudley (1913 – 1989)",
    tag: "Jazz pianist, arranger, and composer",
    bio: "https://en.wikipedia.org/wiki/Dudley_Brooks",
    image: "/images/Dudley-brooks.jpg",
    alt: "Dudley Brooks",
    category: "piano",
  },
  {
    name: "Charles, Ray (1930 – 2004)",
    tag: "American singer, songwriter, pianist, composer",
    bio: "https://en.wikipedia.org/wiki/Ray_Charles",
    image: "/images/RayCharles.jpg",
    alt: "Ray Charles",
    category: "piano",
  },
  {
    name: "Coleman, Steve (b. 1956)",
    tag: "Saxophonist, composer, and bandleader",
    bio: "https://en.wikipedia.org/wiki/Steve_Coleman",
    image: "/images/stevecoleman.jpg",
    alt: "Steve Coleman",
    category: "woodwinds",
  },
  {
    name: "Coleman, Valerie",
    tag: "Flutist and Composer",
    bio: "https://www.vcolemanmusic.com/about.html",
    image: "/images/valerie-coleman.jpg",
    alt: "Valerie Coleman",
    category: "woodwinds",
  },
  {
    name: "Coltrane, Alice (1937 – 2007)",
    tag: "Composer and American jazz pianist",
    bio: "https://www.alicecoltrane.com/",
    image: "/images/alice-coltrane.jpg",
    alt: "Alice Coltrane",
    category: "piano",
  },
  {
    name: "Coltrane, John (1926 – 1967)",
    tag: "Composer and saxophonist",
    bio: "https://en.wikipedia.org/wiki/John_Coltrane",
    image: "/images/john-coltrane.jpg",
    alt: "John Coltrane",
    category: "woodwinds",
  },
  {
    name: "Cooper, Eric ",
    tag: "Cellist",
    bio: "https://www.classical915.org/post/eric-cooper-cello",
    image: "/images/eric-cooper.jpg",
    alt: "Eric Cooper",
    category: "strings",
  },
  {
    name: "Cunningham, Arthur (1928-1997)",
    tag: "Composer & Pianist ",
    bio: "http://chevalierdesaintgeorges.homestead.com/Cunningham.html",
    image: "/images/arthurCunningham.jpg",
    alt: "Arthur Cunningham",
    category: "piano",
  },

  {
    name: "Curtis, Lamar Carey",
    tag: "Bassoonist",
    bio: "https://www.classical915.org/post/lamar-carey-curtis-bassoon",
    image: "/images/curtis__lamar.jpg",
    alt: "Lamar Carey Curtis",
    category: "woodwinds",
  },
  {
    name: "Dabney, Ford Thompson (1883 – 1958)",
    tag: "Pianist, composer, songwriter",
    bio: "https://en.wikipedia.org/wiki/Ford_Dabney",
    image: "/images/ford-dabney.jpg",
    alt: "Ford Dabney",
    category: "piano",
  },
  {
    name: "Davis, Miles Dewey (1926 – 1991)",
    tag: "Trumpeter, bandleader, composer",
    bio: "https://en.wikipedia.org/wiki/Miles_Davis",
    image: "/images/Miles_Davis.jpg",
    alt: "Miles Davis",
    category: "brass",
  },
  {
    name: "Dédé, Edmund (1827-1903)",
    tag: "Composer, Violinist & Conductor ",
    bio: "http://chevalierdesaintgeorges.homestead.com/Dede.html",
    image: "/images/edmund-dede.jpg",
    alt: "Edmund Dede",
    category: "strings",
  },
  {
    name: "Dett, R. Nathaniel (1882-1943) ",
    tag: "Composer, Pianist & Choral Director",
    bio: "http://chevalierdesaintgeorges.homestead.com/Dett.html",
    image: "/images/nathaniel-dett2.jpg",
    alt: "Nathaniel Dett",
    category: "piano",
  },
  {
    name: "Doggett, William Ballard (1916 – 1996)",
    tag: "Pianist, organist and composer",
    bio: "https://en.wikipedia.org/wiki/Bill_Doggett",
    image: "/images/doggettbill.jpg",
    alt: "Bill Doggett",
    category: "piano",
  },
  {
    name: "Elie, Justin (1883-1931)",
    tag: "Haitian Composer & Pianist ",
    bio: "http://chevalierdesaintgeorges.homestead.com/Elie.html",
    image: "/images/Justin_Elie.jpg",
    alt: "Justin Elie",
    category: "piano",
  },
  {
    name: 'Ellington, "Duke" (1899 – 1974)',
    tag: "Composer, pianist, bandleader",
    bio: "https://en.wikipedia.org/wiki/Duke_Ellington",
    image: "/images/Duke_Ellington.jpg",
    alt: "Duke Ellington",
    category: "piano",
  },
  {
    name: 'Ellis, Alfred "Pee Wee" (b.1941)',
    tag: "Saxophonist, composer, arranger",
    bio: "https://en.wikipedia.org/wiki/Alfred_%22Pee_Wee%22_Ellis",
    image: "/images/Pee_Wee_Ellis.jpg",
    alt: "Pee Wee Ellis",
    category: "woodwinds",
  },
  {
    name: "Ellis, Monica",
    tag: "Bassoonist",
    bio: "https://www.msmnyc.edu/faculty/monica-ellis/",
    image: "/images/Monica-Ellis.jpg",
    alt: "Monica Ellis",
    category: "woodwinds",
  },
  {
    name: "Farquharson, Wilfred",
    tag: "Violist",
    bio: "https://www.laco.org/people/wilfred-farquharson/",
    image: "/images/wilfred-F.jpg",
    alt: "Wilfred Farquharson",
    category: "strings",
  },
  {
    name: "Fisher, Frank R. (b.1926)",
    tag: "Trumpeter, composer, arranger",
    bio: "https://en.wikipedia.org/wiki/Frank_R._Fisher",
    image: "/images/frank-fisher.jpg",
    alt: "Frank Fisher",
    category: "brass",
  },
  {
    name: "Fuller, Michael",
    tag: "Double Bassist",
    bio: "https://www.laphil.com/musicdb/artists/6307/michael-fuller",
    image: "/images/michael-fuller.jpg",
    alt: "Michael Fuller",
    category: "strings",
  },
  {
    name: "George, Brandon Patrick",
    tag: "Flutist",
    bio: "https://www.brandonpatrickgeorge.com/about",
    image: "/images/brandon-george.jpg",
    alt: "Brandon Patrick George",
    category: "woodwinds",
  },
  {
    name: 'Gillespie, "Dizzy" (1917 – 1993)',
    tag: "Trumpeter, composer, bandleader",
    bio: "https://en.wikipedia.org/wiki/Dizzy_Gillespie",
    image: "/images/dizzy_gillespie.jpg",
    alt: "Dizzy Gillespie",
    category: "brass",
  },
  {
    name: "Grubbs, Gordon",
    tag: "Cellist",
    bio: "https://www.classical915.org/post/gordon-grubbs-cello",
    image: "/images/grubbs__gordon.jpg",
    alt: "Gordon Grubbs",
    category: "strings",
  },
  {
    name: "Hancock, Herbert Jeffrey (b.1940)",
    tag: "Pianist, composer, bandleader",
    bio: "https://en.wikipedia.org/wiki/Herbie_Hancock",
    image: "/images/herbie-hancock.jpg",
    alt: "Herbie Hancock",
    category: "piano",
  },
  {
    name: "Hawkins, Erskine Ramsay (1914 – 1993)",
    tag: "Trumpeter, bandleader, composer",
    bio: "https://en.wikipedia.org/wiki/Erskine_Hawkins",
    image: "/images/Erskine_Hawkins.jpg",
    alt: "Erskine Hawkins",
    category: "brass",
  },
  {
    name: "Henderson, Fletcher (1897 – 1952)",
    tag: "Pianist, bandleader, composer, arranger",
    bio: "https://en.wikipedia.org/wiki/Fletcher_Henderson",
    image: "/images/Fletcher_Henderson.jpg",
    alt: "Fletcher Henderson",
    category: "piano",
  },
  {
    name: "Henderson, Luther (1919 – 2003)",
    tag: "Arranger, composer, orchestrator, and pianist",
    bio: "https://en.wikipedia.org/wiki/Luther_Henderson",
    image: "/images/Luther-Lincoln-Henderson-Jr.jpg",
    alt: "Luther Henderson",
    category: "piano",
  },
  {
    name: "Herbert, Philip",
    tag: "Composer, conductor, and pianist",
    bio: "http://www.philipherbert.org/about",
    image: "/images/Philip+Aneurin+Herbert.jpg",
    alt: "Philip Herbert",
    category: "piano",
  },
  {
    name: "Hicks Jr., John Josephus (1941 – 2006) ",
    tag: "Composer, arranger and pianist",
    bio: "https://en.wikipedia.org/wiki/John_Hicks_(pianist)",
    image: "/images/john-hicks.jpg",
    alt: "John Hicks",
    category: "piano",
  },
  {
    name: "Holland, Justin  (1819-1887) ",
    tag: "Composer, Guitarist & Teacher",
    bio: "http://chevalierdesaintgeorges.homestead.com/Holland.html",
    image: "/images/Justin_Holland_crop_Z.jpg",
    alt: "Justin Holland",
    category: "strings",
  },
  {
    name: "Hood, Joshua",
    tag: "Bassoonist",
    bio: "https://coaa.uncc.edu/people/joshua-hood",
    image: "/images/Josh_Hood.jpg",
    alt: "Joshua Hood",
    category: "woodwinds",
  },
  {
    name: "Hopson, Sidney ",
    tag: "Percussionist",
    bio: "https://www.linkedin.com/in/sidney-j-hopson-9990027",
    image: "/images/sydney-hopson.jpg",
    alt: "Sidney Hopson",
    category: "percussion",
  },
  {
    name: "Irvine Jr., Weldon Jonathan (1943 – 2002)",
    tag: "Composer, poet and pianist",
    bio: "https://en.wikipedia.org/wiki/Weldon_Irvine",
    image: "/images/weldon-irvine.jpg",
    alt: "Weldon Irvine Jr.",
    category: "piano",
  },
  {
    name: "Jackson, Ron (b. 1964)",
    tag: "Guitarist, composer, arranger",
    bio: "https://en.wikipedia.org/wiki/Ron_Jackson_(jazz_musician)",
    image: "/images/Ron_Jackson.jpg",
    alt: "Ron Jackson",
    category: "strings",
  },
  {
    name: "Jefferson, Tyrone (b.1953)",
    tag: "Trombonist, composer, arranger",
    bio: "https://en.wikipedia.org/wiki/Tyrone_Jefferson",
    image: "/images/Tyrones_Promo.jpg",
    alt: "Tyrone Jefferson",
    category: "brass",
  },
  {
    name: "Jenkins, Leroy (1932 – 2007)",
    tag: "Composer and violinist",
    bio: "https://en.wikipedia.org/wiki/Leroy_Jenkins_(musician)",
    image: "/images/leroy-jenkins.jpg",
    alt: "Leroy Jenkins",
    category: "strings",
  },
  {
    name: "Johnson, James Price (1894 – 1955)",
    tag: "Pianist and composer",
    bio: "https://en.wikipedia.org/wiki/James_P._Johnson",
    image: "/images/james-johnson.jpg",
    alt: "James Price Johnson",
    category: "piano",
  },
  {
    name: "Jones, Shawn",
    tag: "Bassoonist",
    bio: "https://www.sanfranciscoballetorchestra.org/shawn-jones/",
    image: "/images/Shawn-Jones.jpg",
    alt: "Shawn Jones",
    category: "woodwinds",
  },
  {
    name: "Jordan, Joe (1882 – 1971)",
    tag: "Composer, pianist and music publisher",
    bio: "https://en.wikipedia.org/wiki/Joe_Jordan_(musician)",
    image: "/images/jordan_pass.jpg",
    alt: "Joe Jordan",
    category: "piano",
  },
  {
    name: "Kemp, Emme",
    tag: "Pianist, vocalist and composer",
    bio: "https://emmekempallmusic.com/",
    image: "/images/emme-kemp.jpg",
    alt: "Emme Kemp",
    category: "piano",
  },
  {
    name: "Kitchings, Irene (c. 1908-1975)",
    tag: "Pianist, bandleader, songwriter",
    bio: "https://en.wikipedia.org/wiki/Irene_Kitchings",
    image: "/images/irene-kitchings.jpg",
    alt: "Irene Kitchings",
    category: "piano",
  },
  {
    name: "Lamothe, Ludovic  (1882-1953)",
    tag: "Haitian Composer & Pianist ",
    bio: "http://chevalierdesaintgeorges.homestead.com/Lamothe.html",
    image: "/images/Ludovic_Lamothe.jpg",
    alt: "Ludovic Lamothe",
    category: "piano",
  },
  {
    name: "Lewis, Anderson Meade (1905 – 1964)",
    tag: "Pianist and composer",
    bio: "https://en.wikipedia.org/wiki/Meade_Lux_Lewis",
    image: "/images/Meade-Lewis.jpg",
    alt: "Meade Lewis",
    category: "piano",
  },
  {
    name: "Lewis, John Aaron (1920 –2001)",
    tag: "Pianist, composer, and arranger",
    bio: "https://en.wikipedia.org/wiki/John_Lewis_(pianist)",
    image: "/images/john-lewis.jpg",
    alt: "John Lewis",
    category: "piano",
  },
  {
    name: "Marsalis, Wynton Learson (b.1961)",
    tag: "Trumpeter, composer, educator",
    bio: "https://en.wikipedia.org/wiki/Wynton_Marsalis",
    image: "/images/Wynton_Marsalis.jpg",
    alt: "Winton Marsalis",
    category: "brass",
  },
  {
    name: "Matthews, Jr., Onzy Durrett (1930 – 1997)",
    tag: "Pianist, singer, arranger and composer",
    bio: "https://en.wikipedia.org/wiki/Onzy_Matthews",
    image: "/images/Onzy_Matthews.jpg",
    alt: "Onzy Durett Matthews",
    category: "piano",
  },
  {
    name: "McGill, Anthony",
    tag: "Clarinet",
    bio: "https://www.anthonymcgill.com/about/biography/",
    image: "/images/anthony-mcgill.jpg",
    alt: "Anthony McGill",
    category: "woodwinds",
  },
  {
    name: "McQueen, Garrett",
    tag: "Bassoonist",
    bio: "http://www.garrettmcqueen.com/biography.html",
    image: "/images/garrett_mcqueen_1.jpg",
    alt: "Garrett McQueen",
    category: "woodwinds",
  },
  {
    name: "Monk, Thelonious Sphere (1917 – 1982)",
    tag: "Pianist and composer",
    bio: "https://en.wikipedia.org/wiki/Thelonious_Monk",
    image: "/images/thelonious-monk.jpg",
    alt: "Thelonious Monk",
    category: "piano",
  },
  {
    name: "Moerane, Michael Mosoeu (1904-1980)",
    tag: "Composer, Teacher, Pianist & Conductor",
    bio: "http://chevalierdesaintgeorges.homestead.com/Moerane.html",
    image: "/images/MichaelMosoeuMoerane.jpg",
    alt: "Michael Moerane",
    category: "piano",
  },
  {
    name: "Morton, Jelly Roll (1890 – 1941)",
    tag: "Pianist, bandleader and composer",
    bio: "https://en.wikipedia.org/wiki/Jelly_Roll_Morton",
    image: "/images/Jelly_Roll_Morton.jpg",
    alt: "Jelly Roll Morton",
    category: "piano",
  },
  {
    name: "Murray, Diedre",
    tag: "Cellist and composer",
    bio: "https://en.wikipedia.org/wiki/Diedre_Murray",
    image: "/images/diedre-murray.jpg",
    alt: "Diedre Murray",
    category: "strings",
  },
  {
    name: "Nelson, Oliver (1932 – 1975)",
    tag: "Composer, saxophonist, and clarinetist",
    bio: "https://en.wikipedia.org/wiki/Oliver_Nelson",
    image: "/images/oliver-nelson.jpg",
    alt: "Oliver Nelson",
    category: "woodwinds",
  },
  {
    name: "Oluo, Ahamefule J.",
    tag: "Trumpeter and composer",
    bio: "https://en.wikipedia.org/wiki/Ahamefule_J._Oluo",
    image: "/images/Ahamefule-oluo.jpg",
    alt: "Ahamefule Oluo",
    category: "brass",
  },
  {
    name: "Parker Jr., Charles (1920 – 1955)",
    tag: "Saxophonist, bandleader and composer",
    bio: "https://en.wikipedia.org/wiki/Charlie_Parker",
    image: "/images/Charlie_Parker.jpg",
    alt: "Charlie Parker",
    category: "woodwinds",
  },
  {
    name: "Parnther, Anthony",
    tag: "Bassoonist and conductor",
    bio: "https://www.anthonyparnther.com/bassoonist",
    image: "/images/anthony-parnther.jpg",
    alt: "Anthony Parnther",
    category: "woodwinds",
  },
  {
    name: "Parrimore, Bradley",
    tag: "Violist",
    bio: "https://www.laco.org/people/bradley-parrimore/",
    image: "/images/bradley-parimore.jpg",
    alt: "Bradley Parrimore",
    category: "strings",
  },
  {
    name: "Patrick, Pat(1929 – 1991)",
    tag: "Saxophonist and composer",
    bio: "https://en.wikipedia.org/wiki/Pat_Patrick_(musician)",
    image: "/images/patpatrick.jpg",
    alt: "Pat Patrick",
    category: "woodwinds",
  },
  {
    name: "Pradel, Alain Pierre (b. 1949) ",
    tag: "Guadeloupean Composer & Pianist ",
    bio: "http://chevalierdesaintgeorges.homestead.com/Pradel.html",
    image: "/images/alan-pradel.jpg",
    alt: "Alain Pradel",
    category: "piano",
  },
  {
    name: "Purse, Bruce",
    tag: "Trumpeter, bandleader and composer",
    bio: "https://en.wikipedia.org/wiki/Bruce_Purse",
    image: "/images/Bruce_Pocketbook_Purse.jpg",
    alt: "Bruce Purse",
    category: "brass",
  },
  {
    name: "Racine, Julio (1945 - 2020) ",
    tag: "Haitian Composer, Arranger & Flutist ",
    bio: "http://chevalierdesaintgeorges.homestead.com/Racine.html",
    image: "/images/JulioRacine.jpg",
    alt: "Julio Racine",
    category: "woodwinds",
  },

  {
    name: "Rocke, Kai",
    tag: "Bassoonist",
    bio: "https://minnesotaorchestra.org/about/who-we-are/orchestra-musicians/330-bassoon/2157-kai-rocke",
    image: "/images/Kai-Rocke_roster.jpg",
    alt: "Kai Rocke",
    category: "woodwinds",
  },
  {
    name: "Saint-Georges, Le Chevalier de (1745-1799)",
    tag: "Afro-French Composer, Violinist & Conductor ",
    bio: "http://chevalierdesaintgeorges.homestead.com/Page1.html",
    image: "/images/Joseph-Bologne-880.jpg",
    alt: "Le Chevalier de Saint-Georges",
    category: "strings",
  },
  {
    name: "Scott, Jeff",
    tag: "French horn and composer",
    bio: "https://www.newschool.edu/mannes/faculty/jeffrey-scott/",
    image: "/images/jeff-scott.jpg",
    alt: "Jeff Scott",
    category: "brass",
  },
  {
    name: "Smith, Brice",
    tag: "Flutist",
    bio: "https://www.bricesmithflute.com/biography",
    image: "/images/brice-smith.jpg",
    alt: "Brice Smith",
    category: "woodwinds",
  },
  {
    name: "Smith, Hale (1925-2009)",
    tag: "Composer, Pianist & Professor",
    bio: "http://chevalierdesaintgeorges.homestead.com/Smith.html",
    image: "/images/HaleSmith.jpg",
    alt: "Hale Smith",
    category: "piano",
  },
  {
    name: "Spellman-Diaz, Toyin",
    tag: "Oboist",
    bio: "https://steinhardt.nyu.edu/people/toyin-spellman-diaz",
    image: "/images/toyin-spellman.jpg",
    alt: "Toyin Spellman-Diaz",
    category: "woodwinds",
  },
  {
    name: "Stone, Maya",
    tag: "Bassoonist",
    bio: "https://www.interharmony.com/artist-teachers-online/Maya-Stone-bassoon",
    image: "/images/maya-stone.jpg",
    alt: "Maya Stone",
    category: "woodwinds",
  },
  {
    name: "Taylor, Malik ",
    tag: "French horn",
    bio: "https://www.laco.org/people/malik-taylor/",
    image: "/images/malik-taylor.jpg",
    alt: "Malik Taylor",
    category: "brass",
  },
  {
    name: "Underwood, Titus",
    tag: "Oboist",
    bio: "https://www.nashvillesymphony.org/about/orchestra-conductors/titus-underwood/",
    image: "/images/titusunderwood.jpg",
    alt: "Titus Underwood",
    category: "woodwinds",
  },
  {
    name: "Walker, George  (1922 - 2018)",
    tag: "Composer & Pianist ",
    bio: "http://chevalierdesaintgeorges.homestead.com/Walker.html",
    image: "/images/george-walker.jpg",
    alt: "George Walker",
    category: "piano",
  },
  {
    name: "Wiggins, Tom (1849 – 1908) ",
    tag: "Composer and pianist",
    bio: "https://en.wikipedia.org/wiki/Blind_Tom_Wiggins",
    image: "/images/Blind_Tom_Wiggins.jpg",
    alt: "Tom Wiggins",
    category: "piano",
  },
  {
    name: "Yeazell, Myles",
    tag: "Cellist",
    bio: "https://www.laco.org/people/myles-yeazell/",
    image: "/images/myles-y.jpg",
    alt: "Myles Yeazell",
    category: "strings",
  },
];
export default instrumentalists;
